### ISSUE TITLE
Crosshair and drowning indicator stay on player death.

### ISSUE THREAD

**Issue by Krzyska-Filip** [TTTReborn/tttreborn#212]
## Prerequisites

- [x] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary
Crosshair stays on player's screen after death that is not suicide.
Same with drowning indicator when you drown.
![image](https://user-images.githubusercontent.com/45741043/131174882-fbb81073-7634-435e-bae3-1e3a1707a4d0.png)

## Expected behavior
Crosshair and drowning indicator should be removed\hidden after player death

## Actual behavior
Both crosshair and drowning indicator are displayed after death.

## Steps to reproduce
To reproduce crosshair bug you have to die while not ending the current round.
To reproduce drowning indicator you have to drown.

**Comment by GravityWolfNotAmused** [comment]
#212
At the moment you are adding the UI elements to the HudEntity parent, so if we set AliveHud's IsEnabled = false we are setting AliveHud and its children to disabled, but we never added children to AliveHud, we add them to the HudEntity's RootPanel.

If we add these panels to AliveHud instead of the parent, we have to redo the UI to be in the correct position which I don't understand fully yet. (sorry)

I foresee that this collection will grow as the game mode does, and so will the time to disable all of the elements. o(n)

With this being said, would you rather collect them all and disable them? or should we redo the UI, so they are in view and add them as a child of AliveHud?

https://github.com/TTTReborn/tttreborn/blob/bd9262f5f9749dde56096db7295066151d8eb24a/code/ui/Hud.cs#L96-L103

**Comment by mzegar** [comment]
Fixed with #212
