### ISSUE TITLE
Ammo System

### ISSUE THREAD

**Issue by AMastryukov** [TTTReborn/tttreborn#63]
Ammo should be stored based on type, and new types should be easily added if required (e.g. a special purchasable weapon that uses a type of ammo that the players cannot acquire in any other way and that is not shared with any other weapon).

**Comment by Fires1** [comment]
Going to toss in my suggested change to this, you can find my attempted solution at Fires1/tttreborn@e330250 .

So with this change the ammo system moves from a fixed AmmoType enum to a growing dictionary of string keys for each specific ammo type.
The ammo type is registered within a players inventory during [TTTWeapon.Spawn](https://github.com/Fires1/tttreborn/blob/e3302509e15b348fcc16770c1cb303a34e658576/code/items/weapons/TTTWeapon.cs#L109). So the player's inventory should only hold values for weapons they have picked up. That is atleast my understanding of how the process currently works within weapon spawning in S&box. 
I haven't encountered any issues within my testing, weapons with the same ammo type have a shared pool of ammo as expected, and new ammo types can be registered and utilized by simply overriding the AmmoType *string* within a weapon definition.
Should be a somewhat cleaner solution versus hardcoding ammo types in.

This is my first contribution to this project, as well as my first bit of tinkering within S&box's environment so I'm still working on understanding fully and getting used to how everything operates. So just keep that in mind. Let me know how everything looks and thoughts on the overall system change.

**Comment by mzegar** [comment]
@Fires1 do you want to open a PR for this?

**Comment by Fires1** [comment]
Notes for some extension stuff to do after merging #167 .

- TTTAmmo.cs Line 57: Possible to optimize the ammo typing process by caching weapons within the ammo entity, then checking that list against the players, rather than a larger, complicated system.
- TTTWeapon.cs Line 164: Move input to drop ammo to a bindable key once that system is up and running.
- Sounds/animations on pickup.

Will update this comment with links as soon as merge is completed.
